version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/cli-framework/package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/cli-hooks/package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/cli-utils/package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/cli-scripts/package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/discover/package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/lab/package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/v1-toolkit/package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/ginvoicing/package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/cli-framework/package.json" }}
          paths:
            - packages/@ionic/cli-framework/node_modules
      - save_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/cli-hooks/package.json" }}
          paths:
            - packages/@ionic/cli-hooks/node_modules
      - save_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/cli-utils/package.json" }}
          paths:
            - packages/@ionic/cli-utils/node_modules
      - save_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/cli-scripts/package.json" }}
          paths:
            - packages/@ionic/cli-scripts/node_modules
      - save_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/discover/package.json" }}
          paths:
            - packages/@ionic/discover/node_modules
      - save_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/lab/package.json" }}
          paths:
            - packages/@ionic/lab/node_modules
      - save_cache:
          key: dependency-cache-{{ checksum "packages/@ionic/v1-toolkit/package.json" }}
          paths:
            - packages/@ionic/v1-toolkit/node_modules
      - save_cache:
          key: dependency-cache-{{ checksum "packages/ginvoicing/package.json" }}
          paths:
            - packages/ginvoicing/node_modules
      - run: npm run lint
      - run: npm run test
      # - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      # - run: npm run publish:ci-4.x -- --yes
    branches:
      only:
        - master
